### ISSUE TITLE
Access Issue: X-ray Spine Dataset Download Link Not Working

### ISSUE THREAD

**Issue by marwankefah** [jacksonhzx95/NFDP#1]
Hi,

Thank you for your excellent work and the comprehensive evaluation presented in your paper and repository. I am currently trying to access the X-ray spine dataset referenced in your study to validate your approach. However, the link provided for the dataset appears to be broken or inaccessible.

May you please provide an alternative link to the dataset, or share the dataset via email if possible? 
My email address is mkfmelbatel@connect.ust.hk

I appreciate your support and look forward to your response.

Best regards,
Marawan Elbatel

**Comment by jacksonhzx95** [comment]
Thank you for your interest in our work and for reaching out regarding the X-ray spine dataset. Unfortunately, I do not have the permission to share the dataset directly. For access to the dataset, I kindly recommend contacting Dr. Shuo Li directly via his email:  slishuo@gmail.com or Dr. Wang (lswang@xmu.edu.cn). They may be able to provide you with further assistance regarding your request. Thanks for your understanding.

**Comment by marwankefah** [comment]
Thanks for your prompt response and guidance.
